### ISSUE TITLE
Support universal binaries (macOS)

### ISSUE THREAD

**Issue by genericptr** [genericptr/FPM#2]
```toml
[target.universal]
   # lipo -create <pathToIntel.a> <pathToArm.a> -output <pathToUniversal.a>
  compiler = [
    "/usr/local/lib/fpc/${LATEST}/ppca64",
    "/usr/local/lib/fpc/${LATEST}/ppcx64"
  ]
```
