### ISSUE TITLE
Parent targets are broken

### ISSUE THREAD

**Issue by genericptr** [genericptr/FPM#6]
For example using the windows target as the parent for console-tests should work but it isn't.

```toml
[target.windows]
  
  parent = "windows"
  compiler = "${FPC_ROOT}/${LATEST}/bin/${ARCH}-win32/fpc.exe"
  libraryPaths = ['./lib/windows']
  unitPaths = ["${UNITS_BASE}/opengl",
               "${UNITS_BASE}/fcl-base",
               "${UNITS_BASE}/fcl-xml",
               "${UNITS_BASE}/fcl-image",
               "${UNITS_BASE}/rtl-objpas"]
  options = ["-Mobjfpc", "-Sm", "-Sc", "-Sg"]

[target.darwin]
  
  compiler = "/usr/local/lib/fpc/${LATEST}/${PPC}"
  frameworkPaths = ["./lib/macos"]
  libraryPaths = ['/usr/local/lib']

[target.console-tests]
  
  parent = "windows"
```
